### ISSUE TITLE
Can't get sample to work

### ISSUE THREAD

**Issue by thaitie** [bsolomon1124/pyfinance#10]
The sample usage of PandasRollingOLS posted as an answer at https://stackoverflow.com/questions/37317727/deprecated-rolling-window-option-in-ols-from-pandas-to-statsmodels no longer works

I confirmed it wasn't a problem with my personal machine by running it on this online compiler
https://repl.it/@SamArthur/InfatuatedRubberyResources

Here's the error which was given on my personal machine as well as the online compiler

```
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    model = PandasRollingOLS(y=y, x=x, window=window)
  File "/home/runner/.site-packages/pyfinance/ols.py", line 738, in __init__
    use_const=use_const)
  File "/home/runner/.site-packages/pyfinance/ols.py", line 377, in __init__
    self.solution = _rolling_lstsq(self.xwins, self.ywins)
  File "/home/runner/.site-packages/pyfinance/ols.py", line 36, in _rolling_lstsq
    return np.squeeze(np.matmul(np.linalg.inv(np.matmul(x.swapaxes(1, 2), x)),
  File "/usr/local/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 532, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/usr/local/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 89, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.linalg.LinAlgError: Singular matrix
```

**Comment by bsolomon1124** [comment]
Hi @thaitie , I've updated with a working example.

> https://stackoverflow.com/a/44486738/7954504

The reason a singular matrix linalg error gets thrown is because a portion of one of the columns in the data is a big chunk of zeros.  (This is mathematically the "right" result though exceptions are never fun.)

It looks like `pandas-datareader` may need an update, because downloading the original sample data, which is supposed to be at monthly frequency, now comes back with daily frequency that is mostly zeros.  In the updated example on StackOverflow, I'm using the download URL directly with monthly frequency.  Let me know if you're not able to reproduce.
